# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Oak Ridge National Laboratory - Advanced Manufacturing Office Tools
email: accawigk@ornl.gov
description: > # this means to ignore newlines until "baseurl:"
A set of The DOE AMO has undertaken an effort to refactor legacy tools that 
were written for the Windows platform into a modern environment. The legacy 
tools (listed and available for download below) were written in a variety of 
programming languages, and the source code considered proprietary, making it 
difficult to keep these tools current with the rapidly changing IT infrastructure. 
This new effort, expected to be completed in late 2018, will provide for an 
extensively more user-friendly, modern and versatile set of tools. Additionally 
there will be more interoperability between the individual tools, and the entire 
suite will be accessible in an open source environment. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  gaccawi

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
